### PR TITLE
That's my /etc/hosts :wink:

### PR DESCRIPTION
**Pull request by hemanth**
Not able to recall the source, must be from HN, but well the list has the contributor's names :)

### CODE REVIEW

**Comment by hemanth** [comment]
Meow @llkats

**Comment by erunion** [comment]
With the exception of the Adobe activation blocking entries that aren't really appropriate for The List, the rest of just from http://someonewhocares.org/hosts/

**Comment by llkats** [comment]
@hemanth Please see the Pull Request Guidelines portion of the README. I'm not just merging domains arbitrarily -- I want there to be thoughtful reasoning behind each entry. The point of the-list is to make a statement about the social impact of content and editorially decisions made by sites we are choosing to block.

Please open a new pull request if you would like to make additions.

**Comment by hemanth** [comment]
@jonursenbach Exactly the link! 

@llkats Sorry about that, will be sending new PR, misread the intentions of this repo.

**Pull request closed without merging**
